name: ${project.name}
version: ${project.version}
description: ${project.description}
author: SkyVox_
website: "http://www.skydhs.com"

# Main class.
main: ${project.groupId}.Core

commands:
  rubi:
    description: "Gerenciar Rubi."
    usage: "/rubi ajuda"
  rubifrag:
    description: "Gerenciar Fragmentos de Rubi."
    usage: "/rubifrag ajuda"